# -*- coding: utf-8 -*-
"""Main plant disease project_YOLO11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xv2g8JC61LRIpItUIOoJI7VuMIpkQIh7
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""**Install YOLO11 via Ultralytics**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics supervision roboflow
import ultralytics
ultralytics.checks()

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/plant_disease/plant_disease

!yolo task=detect mode=train model=yolo11n.pt data= data.yaml epochs=50 imgsz=640 plots=True cache="False" seed=42 batch=32

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/plant_disease/plant_disease

!yolo task=detect mode=train model=yolo11n.pt data= data.yaml epochs=100 imgsz=640 plots=True cache="False" batch=16

!ls runs/detect/train/

from IPython.display import Image as IPyImage
IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/train4/confusion_matrix.png', width=1000)

IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/train4/confusion_matrix_normalized.png', width=1000)

IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/train4/results.png', width=1000)

IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/train4/val_batch0_labels.jpg', width=1000)

IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/train4/val_batch1_pred.jpg', width=1000)

!yolo task=detect mode=val model=/content/drive/MyDrive/plant_disease/runs/detect/train4/weights/best.pt data=data.yaml

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/runs/detect/train5/weights/best.pt conf=0.25 source=/content/drive/MyDrive/plant_disease/Test/images save=True

IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/predict/Train_1465.jpg', width=1000)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt conf=0.3 source=/content/drive/MyDrive/plant_disease/Test/images/Train_801.jpg

IPyImage(filename='/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/predict2/Train_801.jpg', width=1000)

from ultralytics import YOLO

# Load your trained model
model = YOLO('/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt')

# Validate on the test set
metrics = model.val(data='/content/drive/MyDrive/plant_disease/plant_disease/data.yaml', split='test')
print(metrics.box.map)  # mAP50-95

from ultralytics import YOLO

# Load your trained model
model = YOLO('/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt')

# Evaluate the model's performance on the test set
metrics = model.val(data='/content/drive/MyDrive/plant_disease/plant_disease/data.yaml')
print(metrics.box.map)  # Print mAP50-95
print(metrics.box.map50)  # Print mAP50
print(metrics.box.map75)  # Print mAP75

from ultralytics import YOLO

# Load your trained model
model = YOLO('/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt')

# Validate on the test set
metrics = model.val(data='/content/drive/MyDrive/plant_disease/plant_disease/data.yaml', split='test')
print(metrics.box.map)  # mAP50-95
print(metrics.box.map50)  # Print mAP50
print(metrics.box.map75)  # Print mAP75

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt source=/content/drive/MyDrive/plant_disease/Test/images

IPyImage(filename='/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/predict/Train_802.jpg', width=800)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt source=/content/drive/MyDrive/plant_disease/Test/images

IPyImage(filename='/content/drive/MyDrive/plant_disease/runs/detect/predict/Train_816.jpg', width=800)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/runs/detect/train2/weights/best.pt source=/content/drive/MyDrive/plant_disease/Test/images

IPyImage(filename='/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/predict/Train_814.jpg', width=800)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train2/weights/best.pt source=/content/drive/MyDrive/plant_disease/Test/images/Train_802.jpg

IPyImage(filename='/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/predict/Train_802.jpg', width=800)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train3/weights/best.pt source=/content/drive/MyDrive/plant_disease/Test/images/Train_803.jpg

IPyImage(filename='/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/predict/Train_857.jpg', width=800)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train3/weights/best.pt source=/content/drive/MyDrive/plant_disease/Test/images/Train_857.jpg

IPyImage(filename='/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/predict/Train_877.jpg', width=800)

!yolo task=detect mode=predict model=/content/drive/MyDrive/plant_disease/plant_disease/runs/detect/train/weights/best.pt source=/content/drive/MyDrive/plant_disease/Val/images/Train_1000.jpg